# Generated by Django 2.1.3 on 2018-11-08 01:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(max_length=100)),
                ('procname', models.CharField(max_length=100)),
                ('created_time', models.DateTimeField()),
                ('modified_time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Mode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mod_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='System',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sys_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='machine',
            name='mode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.Mode'),
        ),
        migrations.AddField(
            model_name='machine',
            name='system',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.System'),
        ),
    ]
