# Generated by Django 2.1.3 on 2018-11-08 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='machine',
            name='listen_port',
            field=models.IntegerField(default=0),
        ),
    ]
