# Generated by Django 2.1.3 on 2018-11-08 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_machine_listen_port'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='machine',
            name='modified_time',
        ),
    ]
