# Generated by Django 2.1.3 on 2018-11-09 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_api'),
    ]

    operations = [
        migrations.AddField(
            model_name='api',
            name='api_cycle',
            field=models.IntegerField(default=0),
        ),
    ]
